export const footData = [
  {
    id: "1",
    name: "Rosted Chicken with Scrambel Egg",
    imgFood: "https://source.unsplash.com/400x300/?fastfood,food",
    author: "foodpeddia",
    category: "",
    ratting: 4,
    price: 30000,
  },
  {
    id: "2",
    name: "Chicken Rosted  ",
    imgFood:
      "https://c.ndtvimg.com/2019-12/5f6fg0l8_keraal-roast-chicken_625x300_14_December_19.jpg",
    author: "foodpeddia",
    category: "",
    ratting: 5,
    price: 35000,
  },
  {
    id: "3",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/400x300/?chicken,burger",
    author: "foodpeddia",
    category: "",
    ratting: 4,
    price: 35000,
  },
  {
    id: "4",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/400x300/?salmon,burger",
    author: "foodpeddia",
    category: "",
    ratting: 3,
    price: 35000,
  },
  {
    id: "5",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/400x300/?beef,burger",
    author: "foodpeddia",
    category: "",
    ratting: 5,
    price: 35000,
  },
  {
    id: "6",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/400x300/?pizza,burger",
    author: "foodpeddia",
    category: "",
    ratting: 5,
    price: 35000,
  },
];
