export const footData = [
  {
    id: "1",
    name: "Rosted Chicken with Scrambel Egg",
    imgFood: "https://source.unsplash.com/featured/?fastfood,food",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
  {
    id: "2",
    name: "Chicken Rosted  ",
    imgFood:
      "https://c.ndtvimg.com/2019-12/5f6fg0l8_keraal-roast-chicken_625x300_14_December_19.jpg",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
  {
    id: "3",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/featured/?chicken,burger",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
  {
    id: "4",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/featured/?salmon,burger",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
  {
    id: "5",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/featured/?beef,burger",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
  {
    id: "6",
    name: "Beef Burger Authentic   ",
    imgFood: "https://source.unsplash.com/featured/?pizza,burger",
    author: "kulina",
    category: "",
    ratting: "4.5",
    price: "35.000",
  },
];
